version: '3.8'
services:
  movies:
    image: uhsay805/movies
    ports:
      - "44:80"
    deploy:
      replicas: 3
  train:
    image: uhsay805/trainnnn
    ports:
      - "55:80"
    deploy:
      replicas: 3
  dth:
    image: uhsay805/dth
    ports:
      - "66:80"
    deploy:
      replicas: 3
  recharge:
    image: uhsay805/recharge
    ports:
      - "77:80"
    deploy:
      replicas: 3
