version: '3.8'
services:
  movies:
    image: uhsay805/movie
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: uhsay805/train
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: uhsay805/dth
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: uhsay805/recharge
    ports:
      - "84:80"
    deploy:
      replicas: 3
